# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET MAUI App (Android)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install .NET MAUI
      shell: pwsh
      run: |
        dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build
      run: dotnet build MauiStoreApp/MauiStoreApp.csproj -c Release -f net7.0-android --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
